### ISSUE TITLE
Méthode DesinsererAdresse

### ISSUE THREAD

**Issue by turcda** [IFT2008-TD/liste_doublement_chainee_squelette#1]
Suggestion d'ajout dans la méthode desinsererDeAdresse:    

void Liste<T>::desinsererDeAdresse(Liste::Noeud *adresse) {
        (adresse->precedent)->suivant = adresse->suivant;
        (adresse->suivant)->precedent = adresse->precedent;
         **delete adresse;**
    }

À moins que ce ne soit pas nécessaire?

**Comment by pascalcharp** [comment]
Bien vu!!! Merci!
